# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3554eb9162dc21db865fbbcfda6c2669ed4c2a6bd02f1bce6ac62bb53cdaff8360ec59c8b97d9292928cc08aa71ed4f23fe54c04650ffdb9a29860511da15d54
  app_id: 57d116940f8f80bc9996bb79b14ba18d2d09cdf8f81d623fecb7b9cebd4466f1
  app_secret: df6a9ba11acac98a08e1175f77135355e401d5e9e3cd42314dbf1e5394545f2c
test:
  secret_key_base: 837d69608e71947ce47d4c5d4e8ccb3890f5ddf23f694c2ff3bed66cff26cb962667c74341bfe9a9f3dfeae9b01a3df634e1ef84af38ba7a8fbd78b2edb1bd1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  app_id: 57d116940f8f80bc9996bb79b14ba18d2d09cdf8f81d623fecb7b9cebd4466f1
  app_secret: df6a9ba11acac98a08e1175f77135355e401d5e9e3cd42314dbf1e5394545f2c
